PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
Prefix : <http://www.semanticweb.org/ramzy/ontologies/2021/3/untitled-ontology-6#>

 
 Select ?product ?profitability ?quant
 where
 {
 ?product :hasProductProfitability ?profitability.
{
Select ?product  (sum(xsd:integer(?quantity)) as ?quant)
where 
{
?customer :belongsToTier ?tier.
?customer :makes ?order.
<<?order :containsProduct ?product>> :hasProductQuantity ?quantity.
FILTER  (regex(str(?tier), "1"))
}
Group by(?product)
}
}
Order by DESC(?profitability)