PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
Prefix : <http://www.semanticweb.org/ramzy/ontologies/2021/3/untitled-ontology-6#>

Select ?node ?tier ?max 
where{
?node rdf:type :Supplier.
?node :belongsToTier ?tier.
?node :hasReliability ?max.
 

{
Select ?tier (MAX(?metric) as ?max) {
?node rdf:type :Supplier.
?node :hasReliability ?metric. 
?node :belongsToTier ?tier.

} 
Group by (?tier)
}
}
